//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<License>\r\n  <Id>decae066-5903-4eb0-92be-e30d3f643990</Id>\r\n  <Type>Standard</Typ" +
            "e>\r\n  <Signature>{0}</Signature>\r\n</License>")]
        public string LicenseContent {
            get {
                return ((string)(this["LicenseContent"]));
            }
            set {
                this["LicenseContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"MIIBKjCB4wYHKoZIzj0CATCB1wIBATAsBgcqhkjOPQEBAiEA/////wAAAAEAAAAAAAAAAAAAAAD///////////////8wWwQg/////wAAAAEAAAAAAAAAAAAAAAD///////////////wEIFrGNdiqOpPns+u9VXaYhrxlHQawzFOw9jvOPD4n0mBLAxUAxJ02CIbnBJNqZnjhE50mt4GffpAEIQNrF9Hy4SxCR/i85uVjpEDydwN9gS3rM6D0oTlF2JjClgIhAP////8AAAAA//////////+85vqtpxeehPO5ysL8YyVRAgEBA0IABH+/L9yIiGzv7O5yqF4tsHtriSqV+6aZlrTI9L1OPIjZuncEdJZQ719QRhDjyv9X2X93qpYa45ZMDuCm+iSh1oc=")]
        public string PublicKey {
            get {
                return ((string)(this["PublicKey"]));
            }
            set {
                this["PublicKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MEYCIQD9eX0ZPXSdwHB9XIGLr2goTZDOslymftbwTnpHRhbd0AIhAJ76sgO1MKi7ZK0x3JxXBRtXK2isC" +
            "sLeY25avd16Q732")]
        public string Signature {
            get {
                return ((string)(this["Signature"]));
            }
            set {
                this["Signature"] = value;
            }
        }
    }
}
